; Script generated by AutoBuilder 0.9f Prototype

#region ---Head--
#include <Constants.au3>
#include <GUIConstantsEx.au3>
#include <Misc.au3>
#include <WindowsConstants.au3>
#include <ButtonConstants.au3>
#RequireAdmin

Global $hGUI,$Button_1,$Button_2,$Button_3,$Button_4,$Button_5,$Button_6,$Button_7,$Button_8,$Button_9,$Button_10,$Button_11,$Button_12
create_form()
#endregion ---Head---

#region --- Form ---

func create_form()
$hGUI=GuiCreate("N.C.R", 332, 132, -1, -1, $WS_OVERLAPPED + $WS_CAPTION + $WS_SYSMENU + $WS_VISIBLE + $WS_CLIPSIBLINGS + $WS_MINIMIZEBOX)

$Button_1 = GuiCtrlCreateButton("Restart PC", 10, 10, 70, 30,-1)
$Button_2 = GuiCtrlCreateButton("Task Manag", 90, 10, 70, 30,-1)
$Button_3 = GuiCtrlCreateButton("Explorer", 170, 10, 70, 30,-1)
$Button_4 = GuiCtrlCreateButton("CMD", 250, 10, 70, 30,-1)
$Button_5 = GuiCtrlCreateButton("Control Panel", 10, 50, 70, 30,-1)
$Button_6 = GuiCtrlCreateButton("Active Direct", 90, 50, 70, 30,-1)
$Button_7 = GuiCtrlCreateButton("Event Viewer", 170, 50, 70, 30,-1)
$Button_8 = GuiCtrlCreateButton("Administrative", 250, 50, 70, 30,-1)
$Button_9 = GuiCtrlCreateButton("Run", 10, 90, 70, 30,-1)
;$Button_10 = GuiCtrlCreateButton("Button_10", 90, 90, 70, 30,-1)
;$Button_11 = GuiCtrlCreateButton("Button_11", 170, 90, 70, 30,-1)
;$Button_12 = GuiCtrlCreateButton("Button_12", 250, 90, 70, 30,-1)

GuiSetState()
endfunc
#EndRegion --- Form ---

#region --- Loop ---
While 1
	$msg = GuiGetMsg()
	Switch GUIGetMsg()
	 Case $Button_1
	    cmdRun('shutdown /r')
	 Case $Button_2
		cmdRun('taskmgr')
	 Case $Button_3
		cmdRun('explorer')
	 Case $Button_4
		run("CMD")
	 Case $Button_5
		Run('control panel')
	 Case $Button_6
		Run('dsa.msc')
	 Case $Button_7
		cmdRun('eventvwr')
	 Case $Button_8
		cmdRun('control admintools')
	 Case $Button_9
		cmdRun('#r')
	 Case $Button_10
		Send('')
	Case $Button_11
	   cmdRun('')
    Case $GUI_EVENT_CLOSE
	   ExitLoop
	EndSwitch
WEnd
#Endregion --- Loop ---

#Region --- Additional Functions ---
Func cmdRun($CMD)
   Run(@ComSpec & " /c " & $CMD, "", @SW_HIDE)
EndFunc
#Endregion --- Additional Functions ---

Exit

